include: lint_option.yaml

analyzer:
  language:
    strict-casts: true
  exclude:
    - lib/pb
    - lib/database.g.dart
    - lib/firebase_options.dart
    - lib/generated

linter:
  rules:
    prefer_relative_imports: false
    public_member_api_docs: false
    lines_longer_than_80_chars: false
    diagnostic_describe_all_properties: false
