name: trade_agent_v2
description: Status of trade agent, let user query analyzed stocks.

publish_to: "none"
version: 3.5.1+38027

environment:
  sdk: ">=2.18.4 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_mobile_ads: ^2.2.0
  flutter_staggered_grid_view: ^0.6.1
  url_launcher: ^6.1.0
  auto_size_text: ^3.0.0
  curved_navigation_bar: ^1.0.3
  http: ^0.13.4
  floor: ^1.2.0
  firebase_core: ^2.2.0
  table_calendar: ^3.0.5
  candlesticks:
    git:
      url: https://github.com/Chindada/candlesticks.git
      ref: master
  in_app_purchase: ^3.0.2
  web_socket_channel: ^2.2.0
  sqflite: ^2.2.0+3
  in_app_purchase_storekit: ^0.3.3
  flutter_localizations: # Add this line
    sdk: flutter
  intl: ^0.17.0
  yaml: ^3.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.10.0
  build_runner: ^2.1.10
  floor_generator: ^1.2.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/cover.png
    - pubspec.yaml

flutter_intl:
  enabled: true
