name: trade_agent_v2
description: Status of trade agent, let user query analyzed stocks.

publish_to: 'none'
version: 3.1.4+38018

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  google_mobile_ads: ^1.2.0
  flutter_staggered_grid_view: ^0.6.1
  url_launcher: ^6.1.0
  auto_size_text: ^3.0.0
  curved_navigation_bar: ^1.0.3
  http: ^0.13.4
  floor: ^1.2.0
  firebase_core: ^1.15.0
  table_calendar: ^3.0.5
  candlesticks:
    git:
      url: https://github.com/Chindada/candlesticks.git
      ref: master
  in_app_purchase: ^3.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2
  build_runner: ^2.1.10
  floor_generator: ^1.2.0

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/cover.png

flutter_intl:
  enabled: true
