name: trade_agent_v2
description: Status of trade agent, let user query analyzed stocks.

publish_to: 'none'
version: 2.1.0+30551

environment:
  sdk: ">=2.16.2 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.4
  http: ^0.13.4
  google_mobile_ads: ^1.2.0
  flutter_staggered_grid_view: ^0.6.1
  url_launcher: ^6.0.20
  auto_size_text: ^3.0.0
  curved_navigation_bar: ^1.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.4
  flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/cover.png
