name: trade_agent_v2
description: Status of trade agent, let user query analyzed stocks.

publish_to: "none"
version: 4.2.0+38038

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  auto_size_text: ^3.0.0
  candlesticks:
    git:
      ref: master
      url: https://github.com/Chindada/candlesticks.git
  curved_navigation_bar: ^1.0.3
  date_format: ^2.0.7
  elegant_notification: ^1.6.4
  firebase_core: ^2.2.0
  floor: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  google_fonts: ^4.0.3
  google_mobile_ads: ^2.2.0
  http: ^0.13.4
  in_app_purchase: ^3.0.2
  in_app_purchase_storekit: ^0.3.3
  intl: ^0.17.0
  numberpicker: ^2.1.1
  percent_indicator: ^4.2.2
  protobuf: ^2.1.0
  sqflite: ^2.2.0+3
  syncfusion_flutter_charts: ^20.3.59
  table_calendar: ^3.0.5
  url_launcher: ^6.1.0
  wakelock: ^0.6.2
  web_socket_channel: ^2.2.0
  yaml: ^3.1.1

dev_dependencies:
  analysis_options: any
  build_runner: ^2.1.10
  floor_generator: ^1.2.0
  flutter_launcher_icons: ^0.12.0
  flutter_lints: ^2.0.1
  flutter_test:
    sdk: flutter

flutter_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/app_icon.png"

flutter:
  uses-material-design: true
  assets:
    - assets/cover.png
    - pubspec.yaml
    - assets/google_fonts/

flutter_intl:
  enabled: true
